# Generated by Django 4.2.1 on 2024-04-22 09:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lsp',
            name='display_picture',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=accounts.models.Profile.upload_path),
        ),
    ]
