# Generated by Django 4.2.1 on 2024-04-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_custommessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custommessage',
            options={},
        ),
    ]
